apiVersion: v1
kind: Service
metadata:
  name: configuration-service
  labels:
    app: configuration-service
spec:
  type: ClusterIP
  selector:
    app: configuration-service
  ports:
    - port: 9999
      targetPort: 9999
