apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-service
  labels:
    app: configuration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configuration-service
  template:
    metadata:
      labels:
        app: configuration-service
    spec:
      containers:
        - name: configuration-service
          image: seeyassine/configuration-service:1.0 # Replace with your image
          ports:
            - containerPort: 9999
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes" # Activate Kubernetes-specific configuration if needed
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: "https://github.com/seeyassine/Spring-laboratoire.git"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS
              value: "config-lab-repo-main"
